version: '3.8'

services:
  backend:
    build: .
    container_name: fyp-backend
    volumes:
      - .:/app
      - data:/app/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: ["bash", "-c", "python manage.py runserver 0.0.0.0:8000"]
    networks:
      - fyp-network

volumes:
  data:

networks:
  fyp-network:
    driver: bridge
