version: '3.9'

services:
 backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fyp-backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
